name: "Template for deploying Azure resources"

on:
  workflow_call:
    inputs:
      subscription_id:
        description: 'The Azure subscription ID'
        required: true
        type: string
      client_id:
        description: 'The Azure client ID'
        required: true
        type: string
      tenant_id:
        description: 'The Azure tenant ID'
        required: true
        type: string
      deployment_name:
        description: 'The name of the deployment'
        required: false
        default: 'deployment'
        type: string
      location:
        description: 'The location for the deployment'
        required: false
        default: 'norwayeast'
        type: string
      template_file:
        description: 'The Bicep template file'
        required: true
        type: string
      parameters_file:
        description: 'The Bicep parameters file'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
  IS_PULL_REQUEST: "${{ github.event_name == 'pull_request' }}"

jobs:
  deploy_resources:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "OIDC Login To Tenant"
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}
        enable-AzPSSession: true
    - name: Infra Deployment
      uses: azure/bicep-deploy@v1
      if: github.event_name != 'pull_request'
      with:
        type: "deployment"
        operation: create
        name: ${{ inputs.deployment_name }}
        location: ${{ inputs.location }}
        scope: subscription
        subscription-id: ${{ inputs.subscription_id }}
        template-file: ${{ inputs.template_file }}
        parameters-file: ${{ inputs.parameters_file }}
